### ISSUE TITLE
Readme postgrest instructions lead to "No such file"

### ISSUE THREAD

**Issue by v-stickykeys** [PursuanceProject/ensue#109]
OSX
<img width="333" alt="screen shot 2018-01-23 at 9 15 21 pm" src="https://user-images.githubusercontent.com/8445610/35315682-9a000076-0082-11e8-9468-701a15f7ba91.png">

Instead of `./postgrest postgrest.conf`
The instructions should read `postgrest postgrest.conf`

**Comment by elimisteve** [comment]
@thevaleriemack Is the `postgrest` binary not in the current dir?

**Comment by elimisteve** [comment]
```
wget https://github.com/begriffs/postgrest/releases/download/v0.4.3.0/postgrest-v0.4.3.0-osx.tar.xz
tar xvf postgrest-v0.4.3.0-osx.tar.xz
```

After those two commands are run, the `postgrest` binary should be in `db/`. Looks like it's not?

**Comment by elimisteve** [comment]
Please let me know where the `postgrest` binary ends up on OS X so I can fix the instructions. Thanks @thevaleriemack!

**Comment by v-stickykeys** [comment]
This works as it is meant to. I don't know what I did haha! Somehow I copied it to my system directory `/usr/local/bin` which is why I am able to run `postgrest` from any directory.

In any case, this shouldn't be a problem for others.

**Comment by elimisteve** [comment]
@thevaleriemack Sounds great, thanks! :+1:
