### ISSUE TITLE
Improve Firefox compatibility

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/ensue#175]
- [ ] "the vertical column buttons don't quite work in firefox, (couldn't get calendar to open) but i tried in chrome and ms-edge and the buttons and calendar work there..."
  - Possible cause: https://bugzilla.mozilla.org/show_bug.cgi?id=1089326

**Comment by howmanywhat** [comment]
The following works in Firefox for PursuanceProject.org's Subscribe button, it has extra styles (gradient and text shadow), the only required styles to retain button's current appearance are `cursor` and `color`. Note how `data-toggle` and `data-target` are used to open the Subscribe dialog without the anchor's `href` (I'll try to figure out the column buttons in the Pursuance front-end next) --
```html
<!--button class="subscribe"><a href="#mc_embed_signup" data-toggle="modal"
class="nav-link">Subscribe to our mailing list here!</a></button>-->
<button type="button" class="subscribe btn-lg" style="color: #beecf7;
cursor: pointer; background: -moz-linear-gradient(top, #f0b111 0%, #f05d0e);
background: -webkit-gradient(linear, left top, left bottom, from(#f0b111), to(#f05d0e));
text-shadow: 0px -1px 0px rgba(000,000,000,0.4), 0px 1px 0px rgba(255,255,255,0.3);"
data-toggle="modal"
data-target="#mc_embed_signup">Subscribe to our mailing list here!</button>
```
- Note 2 -- tested the html in Chrome, the appearance and functionality are the same
- Note 3 -- also works in Edge (added site's current code to above html for bugzilla ref -- current code works fine in Chrome and Edge but not Firefox)
- OS: Windows 10

| Browser | Version |
| --- | --- |
| Firefox | 60.0.1 (64-bit) |
| Chrome | 66.0.3359.181 (Official Build) (64-bit) |
| Edge | 41.16299.402.0, EdgeHTML 16.16299 |

Here's what the button looks like with the extra styles:
![samplestyles](https://user-images.githubusercontent.com/39198990/39971998-3e838d6e-56d4-11e8-823f-4f6336cc42c7.PNG)

(edit typos, added `cursor: pointer`, Notes 2, 3, image showing the additional styles, and code Markdown, OS and browser version #s)
