### ISSUE TITLE
New pursuance-specific section: Recruit

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/ensue#221]
1. 2 sections (as tabs up top?): "Create invite link" and "Recruit by skill set"

2. "Create invite link"
  - "Invite people who don't have an account on this website into this pursuance"
  - Allow the generation of invite links
  - Each link invites a user at a specific permissions level
  - Later: let users choose how long the link lasts until it expires (if ever)

3. "Recruit by skill set"
  - "Find users who already have an account on this website into this pursuance"
  - Form fields: interests, skills, username
  - There should be a form up top and 2 tag clouds to the right: one for "interests", the other for "skills"
    - Or just show a tag cloud for skills and not interests
  - Clicking on a word in the tag cloud to the right turns the clicked-on word purple (should start out as blue) and adds it to the appropriate form field

**Comment by 4xdk** [comment]
Maybe this would be best situated on the Participants page?

**Comment by elimisteve** [comment]
Well the "participants" are the people already in your pursuance, so
recruiting people on the same server who are _not_ in your pursuance, or
inviting people to your pursuance who aren't on the server at all, are
different things than viewing (or modifying) the people already involved...
but it is related...

**Comment by 4xdk** [comment]
Akin to having 'find more friends' CTA placed on 'your friends' page on your social network of choice.
