### ISSUE TITLE
Firefox can't talk to PostgREST correctly

### ISSUE THREAD

**Issue by NOTtheMessiah** [PursuanceProject/ensue#57]
Instead of calling _http://localhost:8082/postgrest/pursuances?select=id,name,description_, when run on Firefox 57 on Linux, it tries calling _http://localhost:8082/undefined/postgrest/pursuances?select=id,name,description_

Steps to reproduce:
- checkout demo branch, initialize database and launch Pursuance.
- Open Firefox and go to localhost:8082
- click Dashboard.

![pursuancefirefox](https://user-images.githubusercontent.com/2946283/32418260-7650c264-c234-11e7-8368-befbabee4f15.png)

**Comment by elimisteve** [comment]
Thanks @NOTtheMessiah! Hopefully the polyfill fixes this for Firefox.

And just to be clear, we will absolutely support Firefox first-class, but to get the demo ready we focused on Chrome/Chromium and only made a couple tweaks to make some things work well in Firefox, but haven't focused on it yet.

All modern browsers will be supported: Chrome/Chromium, Firefox, Mobile Safari, and IE11+.
