### ISSUE TITLE
migrate.sh doubt as to purpose, plus need to create file if not present?

### ISSUE THREAD

**Issue by sharkberto** [PursuanceProject/ensue#63]
https://github.com/PursuanceProject/pursuance/blob/dd284045a1a9d7cf48db154b6b63edab838a0ee3/db/migrate.sh#L7

Don't understand purpose of "Run migrations" at end of init script. Also, file not detected or can't be created via init_sql.sh? Got this error.
`
migrate.sh: line 9: sql/migration*.sql: No such file or directory`

Thanks

**Comment by elimisteve** [comment]
Hi @sharkberto!  `init_sql.sh` does a bunch of database stuff, including creating tables and then making changes to those tables or something else in the schema (e.g., adding a column or function) in `sql/migration*.sql` files.

The `develop` branch you were likely using for this was out of date but is now very much up to date; running the `init_sql.sh` as specified in the README should now work perfectly.  Let me know it it doesn't.

Pursuance dev chat server, in case you'd like to join us: https://bit.ly/cwc-mminvite . Look for the `pursuance` channel.
