### ISSUE TITLE
Integrate `prettier` for code linting

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/ensue#64]
See https://github.com/prettier/prettier and https://prettier.io

**Comment by Spetastian** [comment]
@elimisteve I can take this one. Could you assign it to me?

**Comment by Spetastian** [comment]
@elimisteve Please check out this one: https://github.com/PursuanceProject/pursuance/pull/70/files Read the description and try it.

**Comment by elimisteve** [comment]
@Spetastian I can't assign this to you until you accept my invite :-) https://github.com/PursuanceProject/pursuance/invitations

**Comment by elimisteve** [comment]
Added by @spetastian!
