### ISSUE TITLE
Feature: list public pursuances at /pursuance/all

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/ensue#80]
@Moe-Shoman Do a GET to `getJSON("/pursuances?is_encrypted=is.false")` to get a list of all public pursuances.  Show each `name`, `mission`, and `created` date

Later we'll also display how many members each pursuance has.

(This page should not require the user to be authenticated, but most of the others we've made should.)

**Comment by v-stickykeys** [comment]
got it! i put it at /all for now. just need to figure out how i can convert the date in react and maybe order by date created?

**Comment by elimisteve** [comment]
@thevaleriemack Sounds good! Want to send me a PR?

**Comment by elimisteve** [comment]
Added by @thevaleriemack!
